apiVersion: v1
kind: Secret
metadata:
  name: smart-mobility-secrets
  namespace: default
type: Opaque
# Values are base64 encoded:
#   echo -n "yourvalue" | base64
stringData:
  DATABASE_URL: "postgresql://ride_user:ride_pass@postgres:5432/ride_db"
  POSTGRES_USER:     "ride_user"
  POSTGRES_PASSWORD: "ride_pass"
  POSTGRES_DB:       "ride_db"
